use_frameworks!

target 'SwiftSkyLab_Example' do
  pod 'SwiftSkyLab', :path => '../'

  target 'SwiftSkyLab_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    
  end
end
